### ISSUE TITLE
there is an error writing the jef file

### ISSUE THREAD

**Issue by fabricocouto** [EmbroidePy/EmbroideryIO#12]
there is an error writing the jef file
in point count i had to add more because it was missing more jumps so with this added here it was perfect with the wilcom program but at the end of the binary file it is saving more points

**Comment by tatarize** [comment]
Does your version have trims or something because I might be off on that count.

Embroidermodder/MobileViewer#96

**Comment by tatarize** [comment]
Should be fixed by #14
